services:
  web:
    build:
      context: .
      dockerfile: build.Dockerfile
    image: bab-aat:latest
    ports:
      - "8080:8080"
    environment:
      DJANGO_SETTINGS_MODULE: "babaatsite.settings"
      SECRETS_BASE_DIR: ""
    command: >
      sh -c "uv run modal token set --token-id $$MODAL_TOKEN_ID --token-secret $$MODAL_TOKEN_SECRET &&
        uvicorn babaatsite.asgi:application
          --host 0.0.0.0
          --port 8080
          --log-level info"
    env_file:
      - ".env"
    volumes:
      - ./resources/media:/app/resources/media
    deploy:
      resources:
        limits:
          memory: 2G

  worker:
    build:
      context: .
      dockerfile: build.Dockerfile
    depends_on:
      - web
    image: bab-aat:latest
    environment:
      DJANGO_SETTINGS_MODULE: "babaatsite.settings"
    command: >
      sh -c "uv run modal token set --token-id $$MODAL_TOKEN_ID --token-secret $$MODAL_TOKEN_SECRET &&
        uv run celery -A babaatsite worker --pool prefork --concurrency 8 --loglevel info"
    env_file:
      - ".env"
    volumes:
      - ./resources/media:/app/resources/media
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 2G
