services:
  web:
    build:
      context: .
      dockerfile: build.Dockerfile
    image: bab-aat:latest
    ports:
      - "8080:8080"
    environment:
      DJANGO_SETTINGS_MODULE: "babaatsite.settings"
      SECRETS_BASE_DIR: ""
    command: >
      uvicorn babaatsite.asgi:application
        --host 0.0.0.0
        --port 8080
        --log-level info
    env_file:
      - ".env"
    volumes:
      - ./resources/media:/app/resources/media

  worker:
    build:
      context: .
      dockerfile: build.Dockerfile
    depends_on:
      - web
    image: bab-aat:latest
    environment:
      DJANGO_SETTINGS_MODULE: "babaatsite.settings"
    command: >
      uv run celery -A babaatsite worker --pool prefork --concurrency 12 --loglevel info
    env_file:
      - ".env"
    volumes:
      - ./resources/media:/app/resources/media
