[supervisord]
nodaemon=true
user=appuser
logfile=/dev/stdout
logfile_maxbytes=0

[program:uvicorn]
command=uvicorn babaatsite.asgi:application --host 0.0.0.0 --port 8080 --log-level info
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A babaatsite worker --pool prefork --concurrency 2 --loglevel info
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
