opencv-python==4.11.0.86
ipykernel==6.29.5
numpy==2.2.2
pandas==2.2.3
Pillow==11.1.0
pypdfium2==4.30.1
seaborn==0.13.2
setuptools==78.1.0
--extra-index-url https://www.paddlepaddle.org.cn/packages/stable/cpu/
paddlepaddle==3.0.0
paddleocr==2.0.1
fitz
psycopg2==2.9.10
django==5.2
python-magic-bin==0.4.14
openpyxl==3.1.5
django-cleanup==9.0.0