# Generated by Django 5.2 on 2025-04-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_detection_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='bbox',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
