# Generated by Django 5.2 on 2025-04-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='page_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
