# Generated by Django 5.2 on 2025-05-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0009_tag_page_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="image",
        ),
    ]
