# Generated by Django 5.2 on 2025-05-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0010_remove_page_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("config", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
