# Generated by Django 5.2 on 2025-05-22 09:29

from django.db import migrations, models


def populate_department_origins(apps, schema_editor):
    Document = apps.get_model("ocr", "Document")
    for doc in Document.objects.filter(document_number__isnull=False):
        if not doc.department_origin:  # Only if not already set
            try:
                # Logic similar to _get_calculated_department_origin
                origin = doc.document_number.split("-")[1].strip().upper()
                doc.department_origin = origin[:10]
                doc.save(update_fields=["department_origin"])
            except IndexError:
                # Handle cases where the format is unexpected for existing data
                pass  # Or set a default, or log


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0012_alter_detection_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="department_origin",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.RunPython(
            populate_department_origins, migrations.RunPython.noop
        ),
    ]
