# Generated by Django 5.2 on 2025-05-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0013_document_department_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="annotated_images",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
