# Generated by Django 5.2.1 on 2025-06-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0014_page_annotated_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="detections",
        ),
        migrations.AddField(
            model_name="detection",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="ocr.tag",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="equipment_tag",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
